# This Makefile compiles the C++ programs in this directory.

# Chapter 9 (The Coding Interview Prep Handbook, by Raydelto Hernandez)

# The -Wall flag enables all compiler's warning messages.
# The -std=c++17 flag specifies the C++ standard to use.
# The -o flag specifies the name of the output file.

FLAGS = -Wall -std=c++17
CXX = g++  # C++ compiler, you can choose among g++, clang++, etc.

linearSearch: 01-linearSearch.cpp
	$(CXX) 01-linearSearch.cpp $(FLAGS) -o linearSearch

binarySearch: 02-binarySearch.cpp
	$(CXX) 02-binarySearch.cpp $(FLAGS) -o binarySearch
