# This Makefile compiles the C++ programs in this directory.

# Chapter 10 [Linked Lists] (The Coding Interview Prep Handbook, by Raydelto Hernandez)

# The -Wall flag enables all compiler's warning messages.
# The -std=c++17 flag specifies the C++ standard to use.
# The -o flag specifies the name of the output file.

FLAGS = -Wall -std=c++17
CXX = g++  # C++ compiler, you can choose among g++, clang++, etc.

doublyLinkedList: 01-doublyLinkedList.cpp
	$(CXX) 01-doublyLinkedList.cpp $(FLAGS) -o doublyLinkedList

stdList: 02-stdList.cpp
	$(CXX) 02-stdList.cpp $(FLAGS) -o stdList
