# This Makefile compiles the C++ programs in this directory.

# Chapter 12 [Sliding Window] (The Coding Interview Prep Handbook, by Raydelto Hernandez)

# The -Wall flag enables all compiler's warning messages.
# The -std=c++17 flag specifies the C++ standard to use.
# The -o flag specifies the name of the output file.

FLAGS = -Wall -std=c++17
CXX = g++  # C++ compiler, you can choose among g++, clang++, etc.

maxSumSubArray: 01-maxSumSubArray.cpp
	$(CXX) 01-maxSumSubArray.cpp $(FLAGS) -o maxSumSubArray

longestRepeating: 02-longestRepeating.cpp
	$(CXX) 02-longestRepeating.cpp $(FLAGS) -o longestRepeating
