# This Makefile compiles the C++ programs in this directory.

# Chapter 15 [Maps] (The Coding Interview Prep Handbook, by Raydelto Hernandez)

# The -Wall flag enables all compiler's warning messages.
# The -std=c++17 flag specifies the C++ standard to use.
# The -o flag specifies the name of the output file.

FLAGS = -Wall -std=c++17
CXX = g++  # C++ compiler, you can choose among g++, clang++, etc.

twoSum: 01-twoSum.cpp
	$(CXX) 01-twoSum.cpp $(FLAGS) -o twoSum

