# This Makefile compiles the C++ programs in this directory.

# Chapter 13 [Queues] (The Coding Interview Prep Handbook, by Raydelto Hernandez)

# The -Wall flag enables all compiler's warning messages.
# The -std=c++17 flag specifies the C++ standard to use.
# The -o flag specifies the name of the output file.

FLAGS = -Wall -std=c++17
CXX = g++  # C++ compiler, you can choose among g++, clang++, etc.

stdQueue: 01-stdQueue.cpp
	$(CXX) 01-stdQueue.cpp $(FLAGS) -o stdQueue

priorityQueue: 02-priorityQueue.cpp
	$(CXX) 02-priorityQueue.cpp $(FLAGS) -o priorityQueue

connectRopes: 03-connectRopes.cpp
	$(CXX) 03-connectRopes.cpp $(FLAGS) -o connectRopes
