# This Makefile compiles the C++ programs in this directory.

# Chapter 11 [Two-Pointer Technique] (The Coding Interview Prep Handbook, by Raydelto Hernandez)

# The -Wall flag enables all compiler's warning messages.
# The -std=c++17 flag specifies the C++ standard to use.
# The -o flag specifies the name of the output file.

FLAGS = -Wall -std=c++17
CXX = g++  # C++ compiler, you can choose among g++, clang++, etc.

findPairSum: 01-findPairSum.cpp
	$(CXX) 01-findPairSum.cpp $(FLAGS) -o findPairSum

reverseArray: 02-reverseArray.cpp
	$(CXX) 02-reverseArray.cpp $(FLAGS) -o reverseArray

listCycle: 03-listCycle.cpp
	$(CXX) 03-listCycle.cpp $(FLAGS) -o listCycle
