# This Makefile compiles the C++ programs in this directory.

# Chapter 7 [Big O Notation] (The Coding Interview Prep Handbook, by Raydelto Hernandez)

# The -Wall flag enables all compiler's warning messages.
# The -std=c++17 flag specifies the C++ standard to use.
# The -o flag specifies the name of the output file.

FLAGS = -Wall -std=c++17
CXX = g++  # C++ compiler, you can choose among g++, clang++, etc.

bubblesort: 01-bubblesort.cpp
	$(CXX) 01-bubblesort.cpp $(FLAGS) -o bubblesort

triplets: 02-triplets.cpp
	$(CXX) 02-triplets.cpp $(FLAGS) -o triplets
