# This Makefile compiles the C++ programs in this directory.

# The -Wall flag enables all compiler's warning messages.
# The -std=c++17 flag specifies the C++ standard to use.
# The -o flag specifies the name of the output file.

FLAGS = -Wall -std=c++17

bubblesort: 01-bubblesort.cpp
	g++ 01-bubblesort.cpp $(FLAGS) -o bubblesort

triplets: 02-triplets.cpp
	g++ 02-triplets.cpp $(FLAGS) -o triplets
